name: Python application

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the `main` branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the `main` branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
    - name: Check out the code
      uses: actions/checkout@v2  # Check out the repository code

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python
      with:
        python-version: '3.8'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Run tests using pytest
